<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPiicfpy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPiicfpy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPiicfpy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPiicfpy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPiicfpy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Piicfpy',
    'container.build_id' => 'dace6b95',
    'container.build_time' => 1534178257,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPiicfpy');
